cors:
  originPatterns: http://localhost:8080,https://rodrigues.com.br,http://localhost:3000

file:
  upload-dir: /Users/yrodr/Desktop/codes/UploadDir

security:
  jwt:
    token:
      secret-key: 53cr37
        expire-length:3600000 # 1 hour
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_course?useTimezone=true&serverTimezone=UTC
    username: dev
    password: 142103

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

springdoc:
  pathsToMatch:
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true